language: go
go: 1.13.x

before_install:
  - make install
  - go get golang.org/x/lint/golint
  - go get github.com/securego/gosec/cmd/gosec

notifications:
  email: false

matrix:
  include:
    - stage: build
      script:
        - make vet
        - make lint
        - make security-check
        - make cyclo-check
        - make test
